name: CodeGuardian

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          
      - name: Run CodeGuardian
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CACHE_DIR: .cache
          CACHE_TTL: 3600
          MAX_RETRIES: 3
          BASE_DELAY: 1.0
          MAX_DELAY: 30.0
          LOG_LEVEL: INFO
        run: python -m codeguardian.main 